fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  lane :test do |options|
    scan(scheme: options[:scheme], device: "iPhone 11 (13.2)")
  end

  lane :beta do
    gym(
      scheme: "Video-Internal",
      export_options: {
        method: "enterprise",
        compileBitcode: false,
        thinning: "<none>",
        signingStyle: "manual",
        signingCertificate: "iPhone Distribution: Twilio, Inc.",
        provisioningProfiles: {
          "com.twilio.video-app-internal" => "VideoApp-Internal-Distribution"
        }
      }
    ) 

    upload_symbols_to_crashlytics()

    appcenter_upload(
      api_token: ENV["APP_CENTER_API_KEY"],
      owner_name: ENV["APP_CENTER_OWNER_NAME"],
      app_name: "Ahoy-Video-App-Internal",
      file: "Video-Internal.ipa"
    )
  end
end
